MAX_REWRITE_ATTEMPTS = 3

HALLUCINATION_THRESHOLD = 0.75
ANSWER_SCORE_THRESHOLD = 0.70

TOP_K_RETRIEVAL = 5

MAX_QUERY_LENGTH = 500
MIN_QUERY_LENGTH = 3

MAX_TENANTS = 50
MAX_DOCS_PER_TENANT = 200

CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200

SEMANTIC_CACHE_SIMILARITY_THRESHOLD = 0.95
SEMANTIC_CACHE_TTL_SECONDS = 3600

DEFAULT_TENANT_QPS_LIMIT = 10
DEFAULT_MONTHLY_TOKEN_BUDGET = 5_000_000

INGESTION_MAX_RETRIES = 3
INGESTION_CHUNK_BATCH_SIZE = 100
FAISS_WRITE_LOCK_TTL_SECONDS = 600
